{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "0c90c91b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "A gerar Gráfico 1 (Série Temporal Detalhada)...\n",
      "A gerar Gráfico 2 (Tendência)...\n",
      "A gerar Gráfico 3 (Boxplot)...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_1576\\3620900990.py:110: MatplotlibDeprecationWarning: The 'labels' parameter of boxplot() has been renamed 'tick_labels' since Matplotlib 3.9; support for the old name will be dropped in 3.11.\n",
      "  bp = axes[idx].boxplot(dados, labels=['Abril', 'Maio'], patch_artist=True)\n",
      "C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_1576\\3620900990.py:110: MatplotlibDeprecationWarning: The 'labels' parameter of boxplot() has been renamed 'tick_labels' since Matplotlib 3.9; support for the old name will be dropped in 3.11.\n",
      "  bp = axes[idx].boxplot(dados, labels=['Abril', 'Maio'], patch_artist=True)\n",
      "C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_1576\\3620900990.py:110: MatplotlibDeprecationWarning: The 'labels' parameter of boxplot() has been renamed 'tick_labels' since Matplotlib 3.9; support for the old name will be dropped in 3.11.\n",
      "  bp = axes[idx].boxplot(dados, labels=['Abril', 'Maio'], patch_artist=True)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "A construir o Super HTML...\n",
      "\n",
      "✅ SUCESSO! O teu 'Super HTML' com todos os dados técnicos foi gerado em:\n",
      "C:/Python/NORZEC/outputs\\portfolio_norzec_super.html\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from datetime import datetime\n",
    "import os\n",
    "import base64\n",
    "from io import BytesIO\n",
    "\n",
    "# =====================================================================\n",
    "# PASSO 1: FUNÇÃO PARA CONVERTER GRÁFICOS EM BASE64\n",
    "# =====================================================================\n",
    "def fig_to_base64(fig):\n",
    "    \"\"\"Guarda o gráfico na memória e converte-o para texto (Base64)\"\"\"\n",
    "    img = BytesIO()\n",
    "    fig.savefig(img, format='png', bbox_inches='tight', dpi=150)\n",
    "    img.seek(0)\n",
    "    return base64.b64encode(img.getvalue()).decode('utf-8')\n",
    "\n",
    "# =====================================================================\n",
    "# PASSO 2: PREPARAÇÃO DA PASTA\n",
    "# =====================================================================\n",
    "pasta_destino = 'C:/Python/NORZEC/outputs'\n",
    "os.makedirs(pasta_destino, exist_ok=True)\n",
    "\n",
    "# =====================================================================\n",
    "# PASSO 3: CARREGAMENTO DOS DADOS (AGORA COM TMIN)\n",
    "# =====================================================================\n",
    "hist_data = {\n",
    "    'data': [f'2026-04-{i:02d}' for i in range(1, 31)],\n",
    "    'beira_tmax': [29, 28, 28, 28, 30, 32, 30, 26, 29, 30, 31, 32, 32, 31, 31, 31, 32, 33, 35, 35, 33, 32, 31, 30, 31, 30, 33, 33, 29, 30],\n",
    "    'beira_tmin': [26, 25, 23, 20, 22, 22, 20, 18, 24, 22, 22, 22, 23, 22, 24, 23, 23, 23, 21, 23, 25, 25, 25, 25, 23, 22, 22, 21, 22, 23],\n",
    "    'chimoio_tmax': [26, 25, 24, 25, 27, 28, 27, 25, 25, 26, 26, 28, 28, 27, 26, 27, 28, 30, 30, 31, 31, 30, 25, 22, 25, 27, 29, 28, 26, 26],\n",
    "    'chimoio_tmin': [20, 19, 18, 16, 18, 17, 18, 18, 18, 17, 16, 17, 18, 17, 20, 20, 17, 19, 18, 21, 22, 19, 21, 18, 19, 17, 19, 19, 18, 21],\n",
    "    'tete_tmax': [32, 31, 33, 33, 33, 36, 35, 34, 30, 32, 33, 32, 36, 35, 35, 35, 34, 36, 36, 37, 37, 37, 36, 32, 33, 35, 35, 36, 35, 35],\n",
    "    'tete_tmin': [22, 23, 24, 20, 22, 20, 20, 18, 22, 22, 22, 21, 24, 23, 25, 24, 24, 23, 23, 27, 23, 23, 23, 23, 25, 24, 24, 21, 22, 25],\n",
    "}\n",
    "\n",
    "forecast_data = {\n",
    "    'data': [f'2026-05-{i:02d}' for i in range(1, 16)],\n",
    "    'beira_tmax': [31, 30, 29, 28, 27, 27, 28, 29, 28, 27, 26, 26, 27, 28, 27],\n",
    "    'beira_tmin': [23, 23, 22, 21, 20, 19, 19, 20, 21, 20, 19, 18, 18, 19, 20],\n",
    "    'chimoio_tmax': [27, 26, 25, 24, 23, 23, 24, 25, 24, 23, 22, 21, 22, 23, 22],\n",
    "    'chimoio_tmin': [20, 19, 18, 17, 16, 15, 15, 16, 17, 16, 15, 14, 14, 15, 16],\n",
    "    'tete_tmax': [35, 34, 32, 31, 30, 30, 31, 32, 31, 30, 28, 28, 29, 30, 29],\n",
    "    'tete_tmin': [24, 23, 22, 21, 20, 19, 19, 20, 21, 20, 19, 18, 18, 19, 20],\n",
    "}\n",
    "\n",
    "df_hist = pd.DataFrame(hist_data)\n",
    "df_forecast = pd.DataFrame(forecast_data)\n",
    "\n",
    "# Configurações do Eixo X partilhadas\n",
    "posicoes_eixo_x = [1, 10, 20, 30, 35, 40, 45]\n",
    "rotulos_eixo_x = ['1 Abr', '10 Abr', '20 Abr', '30 Abr', '5 Mai', '10 Mai', '15 Mai']\n",
    "todas_datas = list(range(1, 31)) + [30+i for i in range(1, 16)]\n",
    "\n",
    "# =====================================================================\n",
    "# PASSO 4: PRÉ-CÁLCULO DAS VARIÁVEIS MATEMÁTICAS (PARA O HTML)\n",
    "# =====================================================================\n",
    "# Calcular a Amplitude Térmica (Delta T = Tmax - Tmin)\n",
    "delta_t_beira = (df_hist['beira_tmax'] - df_hist['beira_tmin']).mean()\n",
    "delta_t_chimoio = (df_hist['chimoio_tmax'] - df_hist['chimoio_tmin']).mean()\n",
    "delta_t_tete = (df_hist['tete_tmax'] - df_hist['tete_tmin']).mean()\n",
    "\n",
    "# =====================================================================\n",
    "# PASSO 5: GERAR OS 3 GRÁFICOS (E CONVERTER PARA BASE64)\n",
    "# =====================================================================\n",
    "print(\"A gerar Gráfico 1 (Série Temporal Detalhada)...\")\n",
    "fig_serie, axes = plt.subplots(1, 3, figsize=(16, 5))\n",
    "dias_hist = range(1, 31)\n",
    "dias_forecast = range(1, 16)\n",
    "\n",
    "for idx, (cidade, col_max, col_min) in enumerate([('Beira', 'beira_tmax', 'beira_tmin'), \n",
    "                                                  ('Chimoio', 'chimoio_tmax', 'chimoio_tmin'), \n",
    "                                                  ('Tete', 'tete_tmax', 'tete_tmin')]):\n",
    "    ax = axes[idx]\n",
    "    ax.fill_between(dias_hist, df_hist[col_min], df_hist[col_max], alpha=0.3, color='#3dd6a0', label='Abril (histórico)')\n",
    "    ax.plot(dias_hist, df_hist[col_max], marker='o', color='#3dd6a0', linewidth=2, markersize=4, label='Tmax Abril')\n",
    "    \n",
    "    dias_forecast_offset = [30 + i for i in dias_forecast]\n",
    "    ax.fill_between(dias_forecast_offset, df_forecast[col_min], df_forecast[col_max], alpha=0.3, color='#4fc3f7', label='Maio (previsão)')\n",
    "    ax.plot(dias_forecast_offset, df_forecast[col_max], marker='s', color='#4fc3f7', linewidth=2, markersize=4, label='Tmax Maio', linestyle='--')\n",
    "    ax.axvline(x=30.5, color='gray', linestyle=':', alpha=0.5)\n",
    "    \n",
    "    # Aplicar o nosso eixo X corrigido!\n",
    "    ax.set_xticks(posicoes_eixo_x)\n",
    "    ax.set_xticklabels(rotulos_eixo_x, rotation=45, ha='right', fontsize=9)\n",
    "    ax.set_title(f'{cidade}', fontweight='bold')\n",
    "    ax.grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "img_serie_b64 = fig_to_base64(fig_serie)\n",
    "plt.close(fig_serie)\n",
    "\n",
    "print(\"A gerar Gráfico 2 (Tendência)...\")\n",
    "fig_tendencia, ax = plt.subplots(figsize=(10, 5))\n",
    "ax.plot(todas_datas, list(df_hist['beira_tmax']) + list(df_forecast['beira_tmax']), marker='o', linewidth=2.5, label='Beira', color='#1a5e63', markersize=4)\n",
    "ax.plot(todas_datas, list(df_hist['chimoio_tmax']) + list(df_forecast['chimoio_tmax']), marker='s', linewidth=2.5, label='Chimoio', color='#3dd6a0', markersize=4)\n",
    "ax.plot(todas_datas, list(df_hist['tete_tmax']) + list(df_forecast['tete_tmax']), marker='^', linewidth=2.5, label='Tete', color='#e8714a', markersize=4)\n",
    "ax.axvline(x=30.5, color='gray', linestyle=':', linewidth=2, alpha=0.5)\n",
    "ax.set_xticks(posicoes_eixo_x)\n",
    "ax.set_xticklabels(rotulos_eixo_x)\n",
    "ax.legend()\n",
    "ax.grid(True, alpha=0.3)\n",
    "img_tendencia_b64 = fig_to_base64(fig_tendencia)\n",
    "plt.close(fig_tendencia)\n",
    "\n",
    "print(\"A gerar Gráfico 3 (Boxplot)...\")\n",
    "fig_box, axes = plt.subplots(1, 3, figsize=(12, 4))\n",
    "for idx, (cidade, col_max) in enumerate([('Beira', 'beira_tmax'), ('Chimoio', 'chimoio_tmax'), ('Tete', 'tete_tmax')]):\n",
    "    dados = [df_hist[col_max], df_forecast[col_max]]\n",
    "    bp = axes[idx].boxplot(dados, labels=['Abril', 'Maio'], patch_artist=True)\n",
    "    for patch, cor in zip(bp['boxes'], ['#3dd6a0', '#4fc3f7']):\n",
    "        patch.set_facecolor(cor); patch.set_alpha(0.6)\n",
    "    axes[idx].set_title(cidade, fontweight='bold')\n",
    "img_boxplot_b64 = fig_to_base64(fig_box)\n",
    "plt.close(fig_box)\n",
    "\n",
    "# =====================================================================\n",
    "# PASSO 6: ESTRUTURAR O SUPER HTML\n",
    "# =====================================================================\n",
    "print(\"A construir o Super HTML...\")\n",
    "\n",
    "html_content = f\"\"\"\n",
    "<!DOCTYPE html>\n",
    "<html lang=\"pt\">\n",
    "<head>\n",
    "    <meta charset=\"UTF-8\">\n",
    "    <title>Portfólio NORZEC | Corredor Beira (Completo)</title>\n",
    "    <style>\n",
    "        :root {{\n",
    "            --primary: #1a5e63; --secondary: #3dd6a0; --bg-color: #f8f9fa; --text-color: #333;\n",
    "        }}\n",
    "        body {{\n",
    "            font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6;\n",
    "            color: var(--text-color); background-color: var(--bg-color); margin: 0; padding: 20px;\n",
    "        }}\n",
    "        .container {{\n",
    "            max-width: 1000px; margin: 0 auto; background: white; padding: 40px;\n",
    "            border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-top: 5px solid var(--primary);\n",
    "        }}\n",
    "        .header {{ text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #eee; }}\n",
    "        .header h1 {{ color: var(--primary); margin-bottom: 5px; }}\n",
    "        h2 {{ color: var(--primary); border-left: 4px solid var(--secondary); padding-left: 10px; margin-top: 40px; }}\n",
    "        h3 {{ color: #444; }}\n",
    "        .alert-box {{ background-color: #fff3cd; color: #856404; padding: 15px; border-left: 4px solid #ffeeba; border-radius: 4px; margin: 20px 0; }}\n",
    "        .image-container {{ text-align: center; margin: 30px 0; }}\n",
    "        .image-container img {{ max-width: 100%; height: auto; border-radius: 8px; border: 1px solid #ddd; }}\n",
    "        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 0.95em; }}\n",
    "        th, td {{ padding: 12px 15px; text-align: center; border-bottom: 1px solid #ddd; }}\n",
    "        th {{ background-color: var(--primary); color: white; }}\n",
    "        td:first-child {{ text-align: left; font-weight: bold; }}\n",
    "        .technical-section {{ background-color: #f1f8f9; padding: 20px; border-radius: 8px; font-size: 0.95em; }}\n",
    "        .footer {{ text-align: center; margin-top: 50px; padding-top: 20px; border-top: 1px solid #eee; color: #888; font-size: 0.9em; }}\n",
    "    </style>\n",
    "</head>\n",
    "<body>\n",
    "    <div class=\"container\">\n",
    "        <div class=\"header\">\n",
    "            <h1>NORZEC · Relatório Integrado Completo</h1>\n",
    "            <p>Corredor Beira | Análise Retrospectiva (Abril) e Prescritiva (Maio)</p>\n",
    "        </div>\n",
    "\n",
    "        <h2>1. Sumário Executivo & Recomendações</h2>\n",
    "        <p>O Corredor Beira caracteriza-se por um padrão térmico robusto e previsível. Em Abril, verificou-se uma correlação regional forte (r≥0.62) e uma qualidade de dados de 100% (sem gaps). O arrefecimento sazonal em Maio traz impactos diretos na operação.</p>\n",
    "        \n",
    "        <div class=\"alert-box\">\n",
    "            <strong>⚠ ALERTA OPERACIONAL:</strong> Prevista queda abrupta de temperatura em Chimoio entre 11-15 de Maio (22°C → 14°C). Risco de humidade elevada e neblina matinal. Adaptar rotas e reforçar campanhas de saúde pública (riscos respiratórios).\n",
    "        </div>\n",
    "\n",
    "        <h2>2. Dados Consolidados (Incluindo Mínimas e Amplitude)</h2>\n",
    "        <table>\n",
    "            <thead>\n",
    "                <tr>\n",
    "                    <th>Cidade</th>\n",
    "                    <th>T. Máx (Abril)</th>\n",
    "                    <th>T. Mín (Abril)</th>\n",
    "                    <th>Amplitude (ΔT)</th>\n",
    "                    <th>T. Máx (Maio Previsto)</th>\n",
    "                    <th>Variação Sazonal</th>\n",
    "                </tr>\n",
    "            </thead>\n",
    "            <tbody>\n",
    "                <tr>\n",
    "                    <td>Beira (Costa)</td>\n",
    "                    <td>{df_hist['beira_tmax'].mean():.1f}°C</td>\n",
    "                    <td>{df_hist['beira_tmin'].mean():.1f}°C</td>\n",
    "                    <td>{delta_t_beira:.1f}°C</td>\n",
    "                    <td>{df_forecast['beira_tmax'].mean():.1f}°C</td>\n",
    "                    <td style=\"color: blue; font-weight: bold;\">{df_forecast['beira_tmax'].mean() - df_hist['beira_tmax'].mean():+.1f}°C</td>\n",
    "                </tr>\n",
    "                <tr>\n",
    "                    <td>Chimoio (Transição)</td>\n",
    "                    <td>{df_hist['chimoio_tmax'].mean():.1f}°C</td>\n",
    "                    <td>{df_hist['chimoio_tmin'].mean():.1f}°C</td>\n",
    "                    <td>{delta_t_chimoio:.1f}°C</td>\n",
    "                    <td>{df_forecast['chimoio_tmax'].mean():.1f}°C</td>\n",
    "                    <td style=\"color: blue; font-weight: bold;\">{df_forecast['chimoio_tmax'].mean() - df_hist['chimoio_tmax'].mean():+.1f}°C</td>\n",
    "                </tr>\n",
    "                <tr>\n",
    "                    <td>Tete (Interior)</td>\n",
    "                    <td>{df_hist['tete_tmax'].mean():.1f}°C</td>\n",
    "                    <td>{df_hist['tete_tmin'].mean():.1f}°C</td>\n",
    "                    <td>{delta_t_tete:.1f}°C</td>\n",
    "                    <td>{df_forecast['tete_tmax'].mean():.1f}°C</td>\n",
    "                    <td style=\"color: blue; font-weight: bold;\">{df_forecast['tete_tmax'].mean() - df_hist['tete_tmax'].mean():+.1f}°C</td>\n",
    "                </tr>\n",
    "            </tbody>\n",
    "        </table>\n",
    "\n",
    "        <h2>3. Análise Gráfica Sazonal (Série Temporal Detalhada)</h2>\n",
    "        <p>A área sombreada representa a amplitude térmica diária (diferença entre máxima e mínima).</p>\n",
    "        <div class=\"image-container\">\n",
    "            <img src=\"data:image/png;base64,{img_serie_b64}\" alt=\"Série Temporal\">\n",
    "        </div>\n",
    "\n",
    "        <h2>4. Sincronização Regional e Tendência</h2>\n",
    "        <div class=\"image-container\">\n",
    "            <img src=\"data:image/png;base64,{img_tendencia_b64}\" alt=\"Tendência\">\n",
    "        </div>\n",
    "\n",
    "        <h2>5. Distribuição de Frequências (Boxplots)</h2>\n",
    "        <div class=\"image-container\">\n",
    "            <img src=\"data:image/png;base64,{img_boxplot_b64}\" alt=\"Boxplot\">\n",
    "        </div>\n",
    "\n",
    "        <div class=\"technical-section\">\n",
    "            <h2>6. Metodologia, Limitações e Próximos Passos</h2>\n",
    "            <h3>Metodologia</h3>\n",
    "            <ul>\n",
    "                <li><strong>Histórico:</strong> Observações diretas no Corredor Beira (01-30 Abril). Sem outliers, totalmente validados.</li>\n",
    "                <li><strong>Previsão:</strong> Modelo ECMWF IFS (referência mundial, grelha 9 km). Horizonte de 15 dias.</li>\n",
    "            </ul>\n",
    "            <h3>Limitações da Modelagem</h3>\n",
    "            <p>A previsão de precipitação tem menor confiabilidade. Eventos extremos raros (<5% de probabilidade) não são perfeitamente capturados pelo modelo. Mudanças locais (urbanização recente) não estão modeladas.</p>\n",
    "            <div class=\"footer\">\n",
    "                <p><strong>NORZEC</strong> · Engenharia, Dados e Inovação</p>\n",
    "                <p>Matematizando incertezas | Gerado em {datetime.now().strftime('%d/%m/%Y %H:%M')}</p>\n",
    "            </div>\n",
    "        </div>\n",
    "    </div>\n",
    "</body>\n",
    "</html>\n",
    "\"\"\"\n",
    "\n",
    "# =====================================================================\n",
    "# PASSO 7: GUARDAR O FICHEIRO\n",
    "# =====================================================================\n",
    "caminho_final = os.path.join(pasta_destino, 'portfolio_norzec_super.html')\n",
    "with open(caminho_final, 'w', encoding='utf-8') as file:\n",
    "    file.write(html_content)\n",
    "\n",
    "print(f\"\\n✅ SUCESSO! O teu 'Super HTML' com todos os dados técnicos foi gerado em:\\n{caminho_final}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
